const colors = {
  white: "#FFFFFF",
  whiteLilac: "#FBFBFE",
  black: "#252525",
  iron: "#E5E5E5",
  mainBlue: "#0366D6",
  dolphinGray: "#D1D5DA4D",
  dolphinGray20: "#0366D633",
  semiGrey: "#D1D5DA1A",
  grey: "#6E7E91",
  semiDark: "#363636B8",
  semiDark72: "#363636",
  darkBlue: "#2188FF",
  darkGray: "rgba(54, 54, 54, 0.72)",
  lightGray3: "#090A3308",
  lightGray2: "#090A3305",
};

const breakpoints = {
  mobile: "767px",
  tablet: "991px",
};

export const themeDark = {
  colors: {
    bodyBackground: colors.black,
    sectionBackground: colors.semiDark72,
    sectionTitle: colors.white,
    switchButtonBackground: colors.darkGray,
    switchButtonBorder: colors.white,
    buttonText: colors.white,
    buttonBorder: colors.white,
    buttonBackground: colors.darkBlue,
    mail: colors.white,
    mailHover: colors.darkBlue,
    icons: colors.white,
    listDot: colors.mainBlue,
    underline: colors.semiGrey,
    text: colors.white,
    header: colors.white,
    border: colors.semiGrey,

    projectName: colors.white,
    link: colors.darkBlue,
    linkHover: colors.darkBlue,
    letstalk: colors.grey,
    aboutMe: colors.white,
    sun: colors.black,
    sunBox: colors.white,
    listItem: colors.white,
    boxShadow: colors.lightGray3,
    boxShadow2: colors.lightGray2,
    projectName: colors.white,
  },

  breakpoint: {
    mobile: breakpoints.mobile,
    tablet: breakpoints.tablet,
    narrow: breakpoints.narrow,
  },
};

export const themeLight = {
  colors: {
    bodyBackground: colors.whiteLilac,
    sectionBackground: colors.white,
    sectionTitle: colors.black,
    switchButtonBackground: colors.iron,
    switchButtonBorder: colors.darkGray,
    buttonText: colors.white,
    buttonBackground: colors.mainBlue,
    mail: colors.black,
    mailHover: colors.mainBlue,
    icons: colors.black,
    listDot: colors.mainBlue,
    underline: colors.dolphinGray,
    text: colors.grey,
    header: colors.black,
    border: colors.dolphinGray,
    borderHover: colors.dolphinGray20,
    projectName: colors.mainBlue,
    link: colors.mainBlue,
    linkHover: colors.darkBlue,
    letstalk: colors.grey,
    aboutMe: colors.black,
    sun: colors.white,
    sunBox: colors.grey,
    listItem: colors.grey,
    boxShadow: colors.lightGray3,
    boxShadow2: colors.lightGray2,
    projectName: colors.mainBlue,
  },

  breakpoint: {
    mobile: breakpoints.mobile,
    tablet: breakpoints.tablet,
    narrow: breakpoints.narrow,
  },
};
